name: my-workflow
on: [push]
jobs:
  upload-static-files-to-s3-and-cypress-test:
    runs-on: ubuntu-latest
    # These permissions are needed to interact with GitHub's OIDC Token endpoint.
    permissions:
      id-token: write
      contents: read
    steps:
    - name: checkout
      uses: actions/checkout@v3

    - name: configure aws credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: arn:aws:iam::001575836389:role/github_actions_role_static
        role-duration-seconds: 900
        aws-region: us-east-2

    # Test locally with cypress then upload to s3 then test again
    - name:  sync files to s3
      run: |
          aws s3 sync . s3://camdenresume